# Development Profile (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/network_movers
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Automatically clean database when migrations fail validation (e.g. checksum mismatch)
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.validate-on-migrate=false


