# Staging Profile (stage)
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-stage}:${DB_PORT:5432}/${DB_NAME:network_movers}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
