# QA Profile (qa)
spring.datasource.url=jdbc:postgresql://postgres-qa:5432/networkmovers_qa
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
