# QA Profile (qa)
spring.datasource.url=jdbc:postgresql://postgres-qa:5432/network_movers
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.endpoint.info.enabled=true
management.info.app.name=network-movers
management.info.app.description=Network Movers backend platform

spring.jpa.show-sql=true
